# Используем официальный образ Ruby
FROM ruby:3.4.1

# Устанавливаем зависимости для работы с Rails (nodejs и yarn)
RUN apt-get update -qq && apt-get install -y nodejs npm && npm install -g yarn

# Устанавливаем google-chrome для тестов Capibara в контейнере
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome*.deb || apt update && apt-get install -f -y

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем Gemfile и Gemfile.lock в рабочую директорию контейнера
COPY Gemfile Gemfile.lock ./

# Устанавливаем гемы
RUN bundle install

# Копируем все остальные файлы приложения
COPY . .

# Открываем порт, на котором будет работать приложение
EXPOSE 3000

# Команда для запуска приложения
CMD ["rails", "server", "-b", "0.0.0.0"]
