#                                           Docker Volumes / Тома докер

version: '3'

services:
  # сервис который у нас будет работать с питоном и джанга (и устанавливать их)
  django:
    build: ./
    # необязательная команда устанавливает название для контейнера
    container_name: django
    # дополнительная команда
    comand: python manage.py runserver 0.0.0.0:8000     # тут для запуска локального сервера (в Джанга есть предустановленный мы его сразу будем запускать). manage.py - спец фаил к которому мы обращаемся через Питон и вызываем команду(тут runserver) 0.0.0.0 - локалхост
    # Указываем тома за счет которых мы сможем соединить папку с хостмашины(сервера) с указанной нами папкой(тут текущей)
    volumes:
      - .:/usr/src/app      # связываем текущую папку с папкой которая прописана в WORKDIR(рабочая директория с хост машины которая будет находиться в контейнере). без этой нстройки не создастся фаил manage.py и другие
    ports:
      - "8000:8000"
    # Описание зависимостей
    depends_on:             # говорит о том что наш сервис (тут django) вступит в зависимость(можем через него обращаться) с другим нашим сервисом (тут pgdb)
      - pgdb

  # Сервис с БД для контейнера (PostgreSQL)
  pgdb:
    image:                                              # Тк для сервиса pgdb мы не делали докерфаил, то описываем все настройки тут(есть в докерхабе)
    environment:
      - POSTGRES_DB=postgres         # переменная названия образа(название после знака равно)
      - POSTGRES_USER=postgres			 # задаем логин
      - POSTGRES_PASSWORD=postgres   # задаем пароль
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/   # создастся папка pgdbdata в рабочей папке проекта и соединяем ее с папкой на сервере по стандартному пути. Это прописывает, что все значения будут храниться на хостмашине и будут связанны с нашей папкой pgdbdata.

# чтобы все коррктно работало необходимо в самом конце добавить еще одну настройку - volumes указывающее на папку(тут pgdbdata)
volumes:
  pgdbdata:           # тут мы задаем что эта папка будет существовать
# тоесть при помощи томов мы можем указваать папки нашего проекта связанные с папками на хостмашине и все данные будут сохранены и теперь после остановки проекта ничего не будет утеряно












#
