version: '3'

# Определяем какие у нас будут volumes, если их не существует то Докер их создаст
volumes:
  pgdbdata:        # определяем что должна быть общая папка (volume) pgdbdata


services:
  # сервис который будет работать с Питоном и Джанга (и устанавливать их)
  django:
    build: ./ # соберем образ Питона с библиотекой Джанга на основе докерфаила из директории "./"
    # необязательная команда устанавливает название для контейнера
    container_name: django
    comand: python manage.py runserver 0.0.0.0:8000 # тут для запуска локального веб сервера (в Джанга есть предустановленный) manage.py - спец фаил к которому мы обращаемся через Питон и вызываем команду runserver 0.0.0.0 - локалхост

    # volumes - указываем какие тома мы хотим примонтировать к этому контейнеру
    volumes:
      - .:/usr/src/app # монтируем текущую папку "." с папкой "/usr/src/app", которая прописана в WORKDIR(рабочая директория которая будет находиться в контейнере)
    ports:
      - "8000:8000"
    # depends_on устанавливает последовательность загрузки контейнеров. (тут: сначала запустится сервис pgdb, потом django)
    depends_on:
      - pgdb # говорит о том что наш сервис (тут django) вступит в зависимость(можем через него обращаться) с другим нашим сервисом, описанным в эом же docker-compose (тут pgdb) Важно что сервис django зависит от сервиса pgbd, а не наоборот. Именно это гарантирует что контейнер с базой данных будет запущен перед контейнером приложения

  # Сервис с БД PostgreSQL
  pgdb:
    # Тк для сервиса pgdb мы не делали докерфаил, то описываем(копируем в докерхабе) все настройки тут
    image: postgres
    environment:
      # Переменные, которые нужны для подключения к БД
      - POSTGRES_DB=postgres         # переменная названия образа(название после знака равно)
      - POSTGRES_USER=postgres			 # задаем логин
      - POSTGRES_PASSWORD=postgres   # задаем пароль
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/   # создастся папка pgdbdata в рабочей папке проекта и соединяем ее с папкой на сервере по стандартному пути "/var/lib/postgresql/data/" на хост машине. Это прописывает, что все значения будут храниться на хостмашине и будут связанны с нашей папкой pgdbdata. Например наша БД с супераользователем сохранится тут и не исчесзнет если остановить контейнер (docker-compose down) и потом запустить его заново














#
