version: '3.1' # (!! устаревшее свойство, больше не используется, теперь без этого свойства компост сам выбирает самую последнюю схему)

# services - все сервисы с образами и настройками, которые будут развернуты. Каждый сервис имеет свой контейнер и все эти контейнеры имеют друг в друга доступ
services:
  # db:  - название конкретного сервиса (можно выбирать любые названия)
  db:
    # image:   - указывам какой образ мы будем стягивать в этот сервис
    image: mariadb:10.3
    # restart:   - настройка перезапуска образа если он остановлен (?изза ошбки? и если перезапустить виртуальную машину, то после рестарта Докер запустит все эти контейнеры ??) (always - перезапускает, no - не перезапускает)
    restart: always
    # environment:   - различные настройки, переменные среды, значения, что понадобятся, например логин и пароль для входа
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe  # задание пароля для MYSQL

  # phpmyadmin: - название другого сервиса (графического интерфейс для баз данных)
  phpmyadmin:
    image: phpmyadmin
    restart: always
    # ports: - характеристика указывающая порты, при помощи которых этот контейнер свяжется "наружу" (HOST:CONTAINER)
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1














#
