# Пример Dockerfile для разработки
FROM node:14

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package.json ./
RUN npm install

# Копируем код приложения
COPY . .

# Открываем порт
EXPOSE 3000

# Команда для запуска приложения в режиме разработки
CMD ["npm", "start"]